# kubernetes/wordpress-db-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
type: Opaque
stringData:
  host: ${DATABASE_HOST}
  database: ${DATABASE_NAME}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}